### ISSUE TITLE
Package control

### ISSUE THREAD

**Issue by k-o-n-s-t** [uds-se/debuggingbook#1]
Currently there is no package control in the book. In order to make it work locally one has to launch the notebook (or `make` it) and manually resolve missing package dependencies. Certainly, one can reuse _requirements.txt_ file from `binder` folder (though, it it not explicit and should be mentioned in the Readme), but it doesn’t have versions pinned, which may not only create problems in the future but also introduce errors if some old incompatible packages had been already installed.
To make it easier to set up the environment one may take `virtualenv` tool, I would highly recommend to use either `pyenv-virtualenv` or `pipenv`.  
The same issue applies to the code archives distributed via the https://www.debuggingbook.org/ website.

**Comment by havrikov** [comment]
I strongly suggest using [`pipenv`](https://pipenv.pypa.io/en/latest/) over all other tools as the most modern option to achieve reproducible builds.

**Comment by andreas-zeller** [comment]
As part of setting up Continuous Integration, the `requirements.txt` file in the root folder now properly lists all packages required. One can 

* check out the repo,
* `pip install` the required packages, and
*  immediately start running tests, check types and more – even create Web pages.

(which is actually what the CI run does after every push)

If one of you can spare a moment, feel free to experiment with this, and update the instructions in `Importing.ipynb` accordingly (notably setting up a `pipenv`)

**Comment by havrikov** [comment]
@andreas-zeller, I have drafted a preliminary description of how to set up [Pipenv](https://pipenv.pypa.io/) in #25.  
However, this is just a temporary solution that is based on the `requirements.txt` compatibility feature of `pipenv`.  

If we were to manually create a `Pipfile` to manage the dependencies, we could even split split out `dev-packages` that are only required for things like exporting to HTML and not required for using the code in the notebooks.  

I suggest we track this in another issue.
