### ISSUE TITLE
Fuzzingbook code sharing

### ISSUE THREAD

**Issue by k-o-n-s-t** [uds-se/debuggingbook#2]
Using git submodules would be more consistent way to share the code between projects and keep things up-to-date.
The simplest way to refactor the current code is to leave soft links as it is, but point them to files in the submodule instead of external `../fuzzingbook`. Other suggestions are welcome.

**Comment by andreas-zeller** [comment]
Problem is currently, the shared parts span much more than just a Python package - the Makefile is shared, scripts are shared, and more. In the longer run, I want to convert both fuzzingbook and debuggingbook to [Jupyter Books](https://jupyterbook.org/), which should result in a much better (and more modern) organization.

**Comment by andreas-zeller** [comment]
You have been heard: There will be a 'shared' folder which holds code used by both projects; the cross-project links are gone.
