### ISSUE TITLE
ipynpublish package

### ISSUE THREAD

**Issue by k-o-n-s-t** [uds-se/debuggingbook#3]
In case one wants to generate a book, html pages, or presentation from the provided notebooks, one can use the `ipypublish` tool (as mentioned in the Makefile). Currently the soft link points to `fuzzingbook/ipypublish` file from _Fuzzingbook_ repo, which is missing (it is in .gitignore). Besides, this tool utilizes some custom rules stored in `ipypublish_plugins` folder. However, the format of these plugins is not supported by the latest version of ipypublish (v0.10.12). The last supported version is quite old v0.6.8.
I would suggest to update these templates, or at least pin the version of `ipypublish` in the Readme.

**Comment by andreas-zeller** [comment]
In the longer run, I want to convert both fuzzingbook and debuggingbook to [Jupyter Books](https://jupyterbook.org/), which should result in a much better (and more modern) organization.
