### ISSUE TITLE
End of Excursion Slicer

### ISSUE THREAD

**Issue by wyjw** [uds-se/debuggingbook#40]
At the End of the Excursion slicer after the section Implementing Dynamic Instrumentation, 

```
with Slicer(log=True) as slicer:
    fun_2(10)
```
works but
    
```
def run_slicer():
    with Slicer() as slicer:
        fun_2(10)
run_slicer() 
```
yields a `ValueError: Cannot find with block`.

My initial guess is that `starting_lineno` has to be subtracted from `frame.f_lineno` in `our_with_block`, although I'm not entirely sure that this works in all cases. 

Thanks!

**Comment by andreas-zeller** [comment]
The above code does not fail when added to the notebook, but it fails when added to `code/Slicer.py` (or when importing `debuggingbook.Slicer` from Python code). Let me investigate.

**Comment by andreas-zeller** [comment]
Thanks! This should now be fixed.
