### ISSUE TITLE
warning: unable to access '.gitignore': Too many levels of symbolic links

### ISSUE THREAD

**Issue by rjc** [uds-se/debuggingbook#43]
I get the above warning after running `git status`:

```
$ git status
warning: unable to access '.gitignore': Too many levels of symbolic links
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

Indeed, it seems a bit convoluted:

    $ ls -l .gitignore 
    lrwxr-xr-x  1 foo  bar  16 Mar 22 16:12 .gitignore -> shared/gitignore
    $ ls -l shared 
    lrwxr-xr-x  1 foo  bar  16 Mar 22 16:12 shared -> notebooks/shared

Any chance to simplify things in order to get rid of the warning?

**Comment by rjc** [comment]
Ping.

**Comment by andreas-zeller** [comment]
Hi @rjc - I don't see this message, but I removed one level of symbolic links for .gitignore. Are things better now?

**Comment by rjc** [comment]
From what I can see, you've merely edited the `.gitignore` file. The issue seems to be the _fact_ that `.gitignore` **itself** _is_ a symbolic link:

```
$ git clone https://github.com/uds-se/debuggingbook.git
Cloning into 'debuggingbook'...
warning: object 0d78b95a4b40ed320caa2abe948790cb26f3a709: gitignoreSymlink: .gitignore is a symlink
# the above line repeated 2709 times with different object IDs
Updating files: 100% (1426/1426), done.
```

Not sure how can you **not** see this. Which version of _Git_ are you using?

```
$ git --version
git version 2.32.0
```

**Comment by andreas-zeller** [comment]
Thanks! I have now made `.gitignore` a regular file, updated from `shared/gitignore`.
