### ISSUE TITLE
DeltaDebugger#ddmin does not minimize to empty input

### ISSUE THREAD

**Issue by TheSilvus** [uds-se/debuggingbook#46]
The minimization implementation does not minimize as I would expect if all inputs cause the failure:
```
def asdf(s):
    assert False
with DeltaDebugger() as dd:
    asdf("test")
print(dd)
```

**Comment by andreas-zeller** [comment]
I'm getting `asdf(s='t')` as a result, so a proper minimization. (with the latest git version). What do you use, get, and expect?

**Comment by andreas-zeller** [comment]
Thanks! The difference between passing input (here: the empty string) and failing input is normally non-empty, but I have added a check for the case that the empty string already fails (which makes sense as it also discovers internal errors). This is now fixed in the latest git version.
