### ISSUE TITLE
Incorrect references to fuzzingbook

### ISSUE THREAD

**Issue by dfpetrin** [uds-se/debuggingbook#72]
**Describe the bug**
There are some places on the "Using Debuggingbook Code in your own Programs" which say "fuzzingbook" where they should say "debugging book".

**To Reproduce**
1. Go to https://www.debuggingbook.org/html/Importing.html
2. Look at items 1 and 2 in the list under the first heading
3. Observe:

> Choose "Resources->Edit as Notebook" in any of the **fuzzingbook.org** pages

> Using pip install **fuzzingbook**

**Expected behavior**
> Choose "Resources->Edit as Notebook" in any of the **debuggingbook.org** pages

> Using pip install **debuggingbook**

**Comment by andreas-zeller** [comment]
Now fixed – thanks a lot! This fix will appear on debuggingbook.org with the next release.
