### ISSUE TITLE
Incorrect state machine diagram in Introduction to Debugging

### ISSUE THREAD

**Issue by dfpetrin** [uds-se/debuggingbook#73]
**Describe the bug**
In the first state machine diagram on the [Introduction to Debugging](https://www.debuggingbook.org/html/Intro_Debugging.html) page, under the heading [Visualizing Code](https://www.debuggingbook.org/html/Intro_Debugging.html#Visualizing-Code), the state machine diagram and accompanying description indicate that "for every character that is not '<', we add the character and stay in the same state".

This is slightly incorrect. When in the "not tag" state and processing a '>' character, the given code will remain in the "not tag" state, but it will skip outputting the '>' character.

**Comment by andreas-zeller** [comment]
Now fixed – thanks a lot! This fix will appear on debuggingbook.org with the next release.
