### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by eyucherin** [uds-se/debuggingbook#75]
**Describe the bug**

Getting this error
<img width="678" alt="Screenshot 2024-11-08 at 4 02 36 PM" src="https://github.com/user-attachments/assets/82e295e2-cefc-4307-b305-594305403ced">

Tried to resolve it with
`pip install bookutils`
`pip install  requirements.txt`

but still failed to install bookutils.

**To Reproduce**
2. Execute the code '....'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Python version [e.g. 3.6]

**Additional context**

**Comment by andreas-zeller** [comment]
Thank you! The `bookutils` module is part of the debuggingbook; and a link to it is located in the same folder as the notebook you are running. So, it should normally be found when you `import` it. Try the following commands before `import bookutils`:

```
import sys
sys.path.append(".")
sys.path.append("shared")
```
With this, the local `booktutils` module should be imported without problems. Enjoy!

In the long run, you should set your `PYTHONPATH` environment variable such that the two above paths are included.
